Repository arangodb/kube-arangodb, pull requests merged in 2018-08, with the labels that each got.

#231 Updated go-driver to latest version
  deps/github.com/arangodb/go-driver/CHANGELOG.md
  deps/github.com/arangodb/go-driver/MAINTAINERS.md
  deps/github.com/arangodb/go-driver/Makefile
  deps/github.com/arangodb/go-driver/collection_document_impl.go
  deps/github.com/arangodb/go-driver/collection_documents.go
  deps/github.com/arangodb/go-driver/edge_collection_documents_impl.go
  deps/github.com/arangodb/go-driver/http/connection.go
  deps/github.com/arangodb/go-driver/test/documents_create_test.go
  deps/github.com/arangodb/go-driver/test/edges_create_test.go
  deps/github.com/arangodb/go-driver/test/vertices_create_test.go
  deps/github.com/arangodb/go-driver/vertex_collection_documents_impl.go
  deps/github.com/arangodb/go-driver/vst/authentication.go
  deps/github.com/arangodb/go-driver/vst/connection.go
  deps/github.com/arangodb/go-driver/vst/protocol/connection.go
  deps/github.com/arangodb/go-driver/vst/protocol/transport.go
  deps/github.com/arangodb/go-driver/vst/response.go
Labels: 2 - Working

#218 Load balancing tests
  pkg/deployment/client_cache.go
  pkg/util/arangod/client.go
  tests/auth_test.go
  tests/change_args_test.go
  tests/cursor_test.go
  tests/deployments_test.go
  tests/immutable_test.go
  tests/load_balancer_test.go
  tests/member_resilience_test.go
  tests/resilience_test.go
  tests/rocksdb_encryption_test.go
  tests/scale_test.go
  tests/service_account_test.go
  tests/simple_test.go
  tests/sync_test.go
  tests/test_util.go
  tests/upgrade_test.go
Labels: 2 - Working, 9 WIP

#232 Applying defaults after immutable fields have been reset
  pkg/apis/deployment/v1alpha/deployment_spec_test.go
  pkg/apis/deployment/v1alpha/server_group_spec.go
  pkg/deployment/deployment.go
Labels: 2 - Working

#233 Updated versions to known "proper" versions
  tests/upgrade_test.go
Labels: 2 - Working

#212 Adjust documentation based on new load balancer support.
  docs/Manual/Deployment/Kubernetes/DriverConfiguration.md
Labels: 2 - Working, 9 WIP

#235 Use go-upgrade-rules to make "is upgrade allowed" decision fixes #234
  Makefile
  pkg/deployment/reconcile/plan_builder.go
Labels: 2 - Working

#236 Use new CurrentImage field to prevent unintended upgrades.
  pkg/apis/deployment/v1alpha/deployment_status.go
  pkg/apis/deployment/v1alpha/plan.go
  pkg/apis/deployment/v1alpha/zz_generated.deepcopy.go
  pkg/deployment/reconcile/action_context.go
  pkg/deployment/reconcile/action_upgrade_current_image.go
  pkg/deployment/reconcile/plan_builder.go
  pkg/deployment/reconcile/plan_executor.go
  pkg/deployment/resources/pod_creator.go
  pkg/deployment/server_api.go
  pkg/util/k8sutil/events.go
Labels: 2 - Working

#237 Include license in upgrade check
  pkg/deployment/reconcile/plan_builder.go
  pkg/util/k8sutil/events.go
Labels: 2 - Working

#242 Trying to stabalize resilience tests
  tests/member_resilience_test.go
Labels: 2 - Working

#219 Documented dashboard usage
  docs/Manual/Deployment/Kubernetes/Dashboards.md
Labels: 4 - Review, Team Clifton

#245 Adding GKE tutorial
  docs/Manual/Tutorials/Kubernetes/GKE.md
  docs/Manual/Tutorials/Kubernetes/gke-clusters-added.png
  docs/Manual/Tutorials/Kubernetes/gke-clusters-ready.png
  docs/Manual/Tutorials/Kubernetes/gke-clusters.png
  docs/Manual/Tutorials/Kubernetes/gke-connect-to-cluster.png
  docs/Manual/Tutorials/Kubernetes/gke-create-cluster.png
  docs/Manual/Tutorials/Kubernetes/gke-edit-cluster.png
  docs/Manual/Tutorials/Kubernetes/gke-show-credentials.png
Labels: 2 - Working, Team Clifton

#243 Reject critical options during validation fixes #207
  pkg/apis/deployment/v1alpha/server_group_spec.go
  pkg/apis/deployment/v1alpha/server_group_spec_test.go
  pkg/util/arangod/options/options.go
  pkg/util/arangosync/options/options.go
Labels: 4 - Review, Team Clifton
