Repository arangodb/kube-arangodb, pull requests merged in 2018-11, with the labels that each got.

#290 UI Fix
  pkg/deployment/cluster_scaling_integration.go
Labels: 2 - Working

#286 Documentation/add aks tutorial
  docs/Manual/Tutorials/Kubernetes/AKS.md
  docs/Manual/Tutorials/Kubernetes/aks-create-auth.png
  docs/Manual/Tutorials/Kubernetes/aks-create-basics.png
  docs/Manual/Tutorials/Kubernetes/aks-create-valid.png
Labels: 2 - Working

#289 adding EKS tutorial
  docs/Manual/Tutorials/Kubernetes/EKS.md
  docs/Manual/Tutorials/Kubernetes/eks-cluster-active.png
  docs/Manual/Tutorials/Kubernetes/eks-clusters.png
  docs/Manual/Tutorials/Kubernetes/eks-create-review.png
  docs/Manual/Tutorials/Kubernetes/eks-create-template.png
  docs/Manual/Tutorials/Kubernetes/eks-stack-ready.png
  docs/Manual/Tutorials/Kubernetes/eks-stack.png
Labels: 2 - Working

#288 Revisited scale up and scale down.
  pkg/apis/deployment/v1alpha/member_status_list.go
  pkg/deployment/reconcile/action_cleanout_member.go
  pkg/deployment/reconcile/action_shutdown_member.go
  pkg/deployment/reconcile/plan_builder.go
  pkg/deployment/reconcile/plan_builder_test.go
Labels: 2 - Working

#291 Make semiautomation files self-contained.
  tests/acceptance/semiautomation/activefailover.yaml
  tests/acceptance/semiautomation/cluster-local-storage.yaml
  tests/acceptance/semiautomation/cluster-sync.yaml
  tests/acceptance/semiautomation/cluster-sync2.yaml
  tests/acceptance/semiautomation/cluster.yaml
  tests/acceptance/semiautomation/helper.fish
  tests/acceptance/semiautomation/local-storage.yaml
  tests/acceptance/semiautomation/single.yaml
  tests/acceptance/semiautomation/test1a.fish
  tests/acceptance/semiautomation/test1b.fish
  tests/acceptance/semiautomation/test1c.fish
  tests/acceptance/semiautomation/test1d.fish
  tests/acceptance/semiautomation/test2a.fish
  tests/acceptance/semiautomation/test2b.fish
  tests/acceptance/semiautomation/test3a.fish
  tests/acceptance/semiautomation/test3b.fish
  tests/acceptance/semiautomation/test3c.fish
  tests/acceptance/semiautomation/test3d.fish
  tests/acceptance/semiautomation/test4a.fish
  tests/acceptance/semiautomation/test4b.fish
  tests/acceptance/semiautomation/test5a.fish
  tests/acceptance/semiautomation/test5b.fish
  tests/acceptance/semiautomation/test5c.fish
  tests/acceptance/semiautomation/test6a.fish
  tests/acceptance/semiautomation/test6b.fish
  tests/acceptance/semiautomation/test6c.fish
  tests/acceptance/semiautomation/test6d.fish
  tests/acceptance/semiautomation/test6e.fish
  tests/acceptance/semiautomation/test6f.fish
  tests/acceptance/semiautomation/test6g.fish
  tests/acceptance/semiautomation/test7a.fish
Labels: 2 - Working

#294 Fixing uninitialised `lastNumberOfServers`.
  pkg/deployment/cluster_scaling_integration.go
Labels: 2 - Working

#297 fixed getLoadBalancerIP to also handle hostnames
  tests/acceptance/semiautomation/helper.fish
Labels: 3 - Testing, Team Clifton

#298 Make timeout configurable.
  tests/acceptance/semiautomation/helper.fish
  tests/acceptance/semiautomation/test1a.fish
  tests/acceptance/semiautomation/test1b.fish
  tests/acceptance/semiautomation/test1c.fish
  tests/acceptance/semiautomation/test1d.fish
  tests/acceptance/semiautomation/test2a.fish
  tests/acceptance/semiautomation/test2b.fish
  tests/acceptance/semiautomation/test3a.fish
  tests/acceptance/semiautomation/test3b.fish
  tests/acceptance/semiautomation/test3c.fish
  tests/acceptance/semiautomation/test3d.fish
  tests/acceptance/semiautomation/test4a.fish
  tests/acceptance/semiautomation/test4b.fish
  tests/acceptance/semiautomation/test5a.fish
  tests/acceptance/semiautomation/test5b.fish
  tests/acceptance/semiautomation/test5c.fish
  tests/acceptance/semiautomation/test6a.fish
  tests/acceptance/semiautomation/test6b.fish
  tests/acceptance/semiautomation/test6c.fish
  tests/acceptance/semiautomation/test6d.fish
  tests/acceptance/semiautomation/test6e.fish
  tests/acceptance/semiautomation/test6f.fish
  tests/acceptance/semiautomation/test6g.fish
  tests/acceptance/semiautomation/test7a.fish
Labels: 2 - Working

#301 Bug fix/fix immutable reset
  pkg/deployment/deployment.go
  tests/immutable_test.go
  tests/upgrade_test.go
Labels: 2 - Working

#302 Fixing imageID retrieval issue when sidecars are injected.
  pkg/deployment/images.go
  pkg/util/k8sutil/images.go
Labels: 9 CLA available
