Repository arangodb/kube-arangodb, pull requests merged in 2018-10, with the labels that each got.

#271 Added `disableIPV6` Spec entry.
  docs/Manual/Deployment/Kubernetes/DeploymentResource.md
  pkg/apis/deployment/v1alpha/deployment_spec.go
  pkg/apis/deployment/v1alpha/deployment_spec_test.go
  pkg/apis/deployment/v1alpha/zz_generated.deepcopy.go
  pkg/deployment/images.go
  pkg/deployment/resources/pod_creator.go
Labels: Team Clifton

#266 Test/templates
  tests/acceptance/.gitignore
  tests/acceptance/activefailover.template.yaml
  tests/acceptance/cluster-local-storage.template.yaml
  tests/acceptance/cluster-scale-1.template.yaml
  tests/acceptance/cluster-scale-2.template.yaml
  tests/acceptance/cluster-scale-3.template.yaml
  tests/acceptance/cluster-scale-4.template.yaml
  tests/acceptance/cluster-sync.template.yaml
  tests/acceptance/cluster.template.yaml
  tests/acceptance/generate.sh
  tests/acceptance/single.template.yaml
Labels: 1 Feature, 3 - Testing, 3 Kubernetes, 4 Linux, supportability

#269 Skip LoadBalancer Test
  Makefile
  tests/load_balancer_test.go
  tests/test_util.go
Labels: 2 - Working, Team Clifton

#265 Updated examples to use version 3.3.17.
  examples/cluster1-with-sync.yaml
  examples/cluster2-with-sync.yaml
  examples/production-cluster.yaml
  examples/simple-cluster.yaml
  examples/single-server.yaml
Labels: 2 - Working, Team Clifton

#264 Unified Readiness Test
  pkg/deployment/resources/pod_creator.go
Labels: 2 - Working, Team Clifton

#258 Use correct templateoptions for helm charts
  tools/manifests/manifest_builder.go
Labels: 9 CLA available, Team Clifton

#252 Add advanced dc2dc to acceptance test.
  docs/design/acceptance_test.md
  tests/acceptance/.gitignore
  tests/acceptance/cluster12-replication.yaml
Labels: 2 - Working

#274 minor fix in template generation
  tests/acceptance/generate.sh
Labels: 2 - Working

#275 Bug fix/scale up error
  pkg/apis/deployment/v1alpha/member_status_list.go
  pkg/deployment/cluster_scaling_integration.go
  pkg/deployment/reconcile/plan_builder.go
  pkg/deployment/resources/secret_hashes.go
Labels: 2 - Working, Team Clifton

#279 When doing tests, always pull the image.
  tests/test_util.go
Labels: 2 - Working

#281 Updated node modules to fix vulnerabilities
  dashboard/package-lock.json
  dashboard/package.json
Labels: 2 - Working

#285 IPv6 revisited
  docs/Manual/Deployment/Kubernetes/DeploymentResource.md
  pkg/apis/deployment/v1alpha/deployment_spec.go
  pkg/apis/deployment/v1alpha/deployment_spec_test.go
  pkg/apis/deployment/v1alpha/zz_generated.deepcopy.go
  scripts/kube_run_tests.sh
  tests/test_util.go
Labels: 2 - Working

#282 Revert "Skip LoadBalancer Test"
  Makefile
  tests/load_balancer_test.go
  tests/test_util.go
Labels: 2 - Working

#283 Bug fix/readiness upgrade fix
  pkg/deployment/resources/pod_creator.go
Labels: 2 - Working

#277 Break PKS Loop
  pkg/apis/deployment/v1alpha/conditions.go
  pkg/apis/deployment/v1alpha/deployment_spec.go
  pkg/apis/deployment/v1alpha/deployment_status.go
  pkg/apis/deployment/v1alpha/deployment_status_members.go
  pkg/apis/deployment/v1alpha/image_info.go
  pkg/apis/deployment/v1alpha/member_status.go
  pkg/apis/deployment/v1alpha/member_status_list.go
  pkg/apis/deployment/v1alpha/plan.go
  pkg/apis/deployment/v1alpha/secret_hashes.go
  pkg/deployment/deployment.go
  pkg/util/times.go
Labels: 2 - Working, Team Clifton

#287 Bug fix/extra crd yaml
  Makefile
  README.md
  docs/Manual/Deployment/Kubernetes/Usage.md
  manifests/.gitignore
  manifests/templates/crd/deployment-replication.yaml
  manifests/templates/crd/deployment.yaml
  scripts/patch_readme.sh
  tools/manifests/manifest_builder.go
  tools/release/release.go
Labels: 2 - Working
