Repository arangodb/kube-arangodb, pull requests merged in 2018-06, with the labels that each got.

#144 Fixes needed to run on latest openshift.
  manifests/templates/deployment/rbac.yaml
  pkg/apis/deployment/v1alpha/deployment.go
  pkg/deployment/images.go
Labels: 9 Review Required

#150 Added no-execute tolerations on operators to failover quicker
  manifests/templates/deployment/deployment.yaml
  manifests/templates/storage/deployment.yaml
Labels: 9 Review Required

#145 Adding syncmaster&worker reconciliation support.
  docs/Manual/Deployment/Kubernetes/DeploymentResource.md
  pkg/apis/deployment/v1alpha/deployment_spec.go
  pkg/apis/deployment/v1alpha/monitoring_spec.go
  pkg/apis/deployment/v1alpha/monitoring_spec_test.go
  pkg/apis/deployment/v1alpha/server_group_spec.go
  pkg/apis/deployment/v1alpha/sync_spec.go
  pkg/apis/deployment/v1alpha/sync_spec_test.go
  pkg/apis/deployment/v1alpha/zz_generated.deepcopy.go
  pkg/deployment/context_impl.go
  pkg/deployment/deployment.go
  pkg/deployment/reconcile/action_context.go
  pkg/deployment/reconcile/action_wait_for_member_up.go
  pkg/deployment/reconcile/context.go
  pkg/deployment/reconcile/plan_builder.go
  pkg/deployment/resources/certificates_client_auth.go
  pkg/deployment/resources/certificates_tls.go
  pkg/deployment/resources/pod_creator.go
  pkg/deployment/resources/secrets.go
  pkg/replication/sync_client.go
  pkg/util/arangod/client.go
  pkg/util/constants/constants.go
  pkg/util/k8sutil/secrets.go
  pkg/util/k8sutil/secrets_test.go
  tests/auth_test.go
  tests/scale_test.go
  tests/simple_test.go
  tests/sync_test.go
  tests/test_util.go
Labels: 9 Review Required

#147 Sync access packages
  deps/github.com/arangodb/arangosync/client/client_cache.go
  docs/Manual/Deployment/Kubernetes/DeploymentReplicationResource.md
  docs/Manual/Deployment/Kubernetes/DeploymentResource.md
  pkg/apis/deployment/v1alpha/sync_external_access_spec.go
  pkg/apis/deployment/v1alpha/zz_generated.deepcopy.go
  pkg/apis/replication/v1alpha/authentication_spec.go
  pkg/apis/replication/v1alpha/endpoint_authentication_spec.go
  pkg/apis/replication/v1alpha/endpoint_spec.go
  pkg/apis/replication/v1alpha/replication_spec.go
  pkg/apis/replication/v1alpha/zz_generated.deepcopy.go
  pkg/deployment/access_package.go
  pkg/deployment/deployment_inspector.go
  pkg/replication/sync_client.go
  pkg/util/constants/constants.go
  pkg/util/k8sutil/events.go
  pkg/util/k8sutil/secrets.go
Labels: 9 Review Required

#151 Cleanup stateless pods that are in terminating state for a long time
  pkg/apis/deployment/v1alpha/server_group.go
  pkg/deployment/resources/pod_cleanup.go
  pkg/util/k8sutil/pods.go
Labels: 9 Review Required

#155 Operator high-availability
  manifests/templates/deployment-replication/deployment-replication.yaml
  manifests/templates/deployment/deployment.yaml
  manifests/templates/storage/deployment.yaml
Labels: 9 Review Required

#152 Allow customization of serviceAccountName for pods
  docs/Manual/Deployment/Kubernetes/DeploymentResource.md
  manifests/templates/test/rbac.yaml
  pkg/apis/deployment/v1alpha/server_group_spec.go
  pkg/apis/deployment/v1alpha/zz_generated.deepcopy.go
  pkg/deployment/images.go
  pkg/deployment/reconcile/plan_builder.go
  pkg/deployment/resources/pod_creator.go
  pkg/util/k8sutil/pods.go
  tests/service_account_test.go
Labels: 9 Review Required

#153 Cleanup long terminating stateful pods
  pkg/apis/deployment/v1alpha/conditions.go
  pkg/apis/deployment/v1alpha/member_status.go
  pkg/deployment/deployment_inspector.go
  pkg/deployment/resources/context.go
  pkg/deployment/resources/member_cleanup.go
Labels: 9 Review Required

#163 Fix endless rotation because of serviceAccount `default`
  pkg/deployment/reconcile/plan_builder.go
Labels: 4 - Review

#161 Improved Service documentation
  docs/Manual/Deployment/Kubernetes/ServicesAndLoadBalancer.md
Labels: 4 - Review

#165 Added finalizer on deployment, used to remove child finalizers on delete
  pkg/deployment/deployment.go
  pkg/deployment/deployment_finalizers.go
  pkg/deployment/deployment_inspector.go
  pkg/util/constants/constants.go
Labels: 4 - Review

#168 Prevent deleting the PV when the PVC has already been attached to it
  pkg/storage/pv_creator.go
Labels: 3 - Testing

#167 Various test improvements
  scripts/kube_create_storage.sh
  tests/cursor_test.go
  tests/service_account_test.go
  tests/simple_test.go
  tests/test_util.go
Labels: 4 - Review

#169 Remove service stickyness
  pkg/deployment/resources/services.go
  pkg/util/k8sutil/services.go
Labels: 4 - Review

#170 Improving documentation
  docs/Manual/Deployment/Kubernetes/Authentication.md
  docs/Manual/Deployment/Kubernetes/DriverConfiguration.md
  docs/Manual/Deployment/Kubernetes/README.md
  docs/Manual/Deployment/Kubernetes/Storage.md
  docs/Manual/Deployment/Kubernetes/Tls.md
  docs/Manual/Deployment/Kubernetes/Troubleshooting.md
  docs/Manual/Deployment/Kubernetes/Upgrading.md
  docs/Manual/Deployment/Kubernetes/Usage.md
Labels: 4 - Review

#172 Avoid overwriting status changes
  pkg/apis/deployment/v1alpha/deployment_status_members.go
  pkg/apis/deployment/v1alpha/member_status_list_test.go
  pkg/deployment/cluster_scaling_integration.go
  pkg/deployment/context_impl.go
  pkg/deployment/deployment.go
  pkg/deployment/deployment_inspector.go
  pkg/deployment/images.go
  pkg/deployment/members.go
  pkg/deployment/reconcile/action_context.go
  pkg/deployment/reconcile/context.go
  pkg/deployment/reconcile/plan_builder.go
  pkg/deployment/reconcile/plan_executor.go
  pkg/deployment/resilience/context.go
  pkg/deployment/resilience/member_failure.go
  pkg/deployment/resources/context.go
  pkg/deployment/resources/member_cleanup.go
  pkg/deployment/resources/pod_cleanup.go
  pkg/deployment/resources/pod_creator.go
  pkg/deployment/resources/pod_inspector.go
  pkg/deployment/resources/pvc_inspector.go
  pkg/deployment/resources/pvcs.go
  pkg/deployment/resources/secret_hashes.go
  pkg/deployment/resources/services.go
Labels: 4 - Review, Team Clifton

#173 Hide "dangerous" functions of MemberStatusList
  pkg/apis/deployment/v1alpha/deployment_status_members.go
  pkg/apis/deployment/v1alpha/member_status_list.go
  pkg/apis/deployment/v1alpha/member_status_list_test.go
  pkg/deployment/members.go
  pkg/deployment/reconcile/action_context.go
  pkg/deployment/resilience/member_failure.go
  pkg/deployment/resources/member_cleanup.go
  pkg/deployment/resources/pod_creator.go
  pkg/deployment/resources/pod_inspector.go
Labels: 4 - Review, Team Clifton

#174 Avoid useless warnings in log
  pkg/deployment/cleanup.go
  pkg/deployment/cluster_scaling_integration.go
  pkg/deployment/deployment_finalizers.go
  pkg/deployment/resources/pod_creator.go
  pkg/deployment/resources/pod_finalizers.go
  pkg/deployment/resources/pod_inspector.go
  pkg/deployment/resources/pvc_finalizers.go
  pkg/deployment/resources/pvc_inspector.go
  pkg/replication/finalizers.go
  pkg/util/k8sutil/finalizers.go
Labels: 4 - Review, Team Clifton

#171 Abort reconcilientation plan on failed cleanout server
  deps/github.com/arangodb/go-driver/Makefile
  deps/github.com/arangodb/go-driver/cluster_impl.go
  deps/github.com/arangodb/go-driver/context.go
  deps/github.com/arangodb/go-driver/cursor_impl.go
  deps/github.com/arangodb/go-driver/test/concurrency_test.go
  deps/github.com/arangodb/go-driver/test/cursor_test.go
  deps/github.com/arangodb/go-driver/test/user_auth_test.go
  deps/github.com/arangodb/go-driver/vst/protocol/chunk.go
  deps/github.com/arangodb/go-driver/vst/protocol/connection.go
  pkg/apis/deployment/v1alpha/member_status.go
  pkg/deployment/context_impl.go
  pkg/deployment/reconcile/action.go
  pkg/deployment/reconcile/action_add_member.go
  pkg/deployment/reconcile/action_cleanout_member.go
  pkg/deployment/reconcile/action_context.go
  pkg/deployment/reconcile/action_remove_member.go
  pkg/deployment/reconcile/action_renew_tls_certificate.go
  pkg/deployment/reconcile/action_rotate_member.go
  pkg/deployment/reconcile/action_shutdown_member.go
  pkg/deployment/reconcile/action_upgrade_member.go
  pkg/deployment/reconcile/action_wait_for_member_up.go
  pkg/deployment/reconcile/context.go
  pkg/deployment/reconcile/plan_builder.go
  pkg/deployment/reconcile/plan_executor.go
  pkg/util/arangod/cleanout_server.go
  pkg/util/arangod/client.go
  pkg/util/k8sutil/events.go
Labels: 4 - Review, Team Clifton

#175 Documenting acceptance test
  docs/design/acceptance_test.md
  docs/design/acceptance_test_platforms.md
  tests/acceptance/activefailover.yaml
  tests/acceptance/cluster-sync.yaml
  tests/acceptance/cluster.yaml
  tests/acceptance/local-storage.yaml
  tests/acceptance/single.yaml
Labels: 2 - Working, Team Clifton

#176 Improved readiness probe, database services only use ready pods
  pkg/apis/deployment/v1alpha/deployment_status_members.go
  pkg/apis/deployment/v1alpha/member_status_list.go
  pkg/deployment/resources/pod_creator.go
  pkg/deployment/resources/pod_inspector.go
  pkg/util/k8sutil/probes.go
  pkg/util/k8sutil/probes_test.go
  pkg/util/k8sutil/services.go
Labels: 4 - Review, Team Clifton

#166 Added unit tests for pv_creator.go
  Makefile
  pkg/storage/provisioner/mocks/mocks.go
  pkg/storage/provisioner/mocks/provisioner.go
  pkg/storage/pv_creator_test.go
Labels: 4 - Review, Team Clifton

#179 Prefer distinct nodes, even when not required
  pkg/storage/pv_creator.go
Labels: 4 - Review, Team Clifton

#177 Added duration test app
  Makefile
  tests/duration/Dockerfile
  tests/duration/README.md
  tests/duration/main.go
  tests/duration/simple/check.go
  tests/duration/simple/error.go
  tests/duration/simple/simple.go
  tests/duration/simple/simple_collection.go
  tests/duration/simple/simple_create.go
  tests/duration/simple/simple_import.go
  tests/duration/simple/simple_query.go
  tests/duration/simple/simple_query_update.go
  tests/duration/simple/simple_read.go
  tests/duration/simple/simple_rebalance.go
  tests/duration/simple/simple_remove.go
  tests/duration/simple/simple_replace.go
  tests/duration/simple/simple_update.go
  tests/duration/test/shuffle.go
  tests/duration/test/test.go
  tests/duration/test_listener.go
  tests/duration/test_loop.go
Labels: 4 - Review, Team Clifton

#180 Min dbserver count is 2. Revert phase when cleanout has failed
  pkg/apis/deployment/v1alpha/server_group_spec.go
  pkg/deployment/cluster_scaling_integration.go
  pkg/deployment/reconcile/action_cleanout_member.go
  pkg/deployment/reconcile/plan_builder.go
Labels: 4 - Review, Team Clifton

#181 Added renewal of deployment TLS CA certificate
  pkg/apis/deployment/v1alpha/plan.go
  pkg/deployment/access_package.go
  pkg/deployment/context_impl.go
  pkg/deployment/reconcile/action_context.go
  pkg/deployment/reconcile/action_renew_tls_ca_certificate.go
  pkg/deployment/reconcile/action_rotate_member.go
  pkg/deployment/reconcile/context.go
  pkg/deployment/reconcile/plan_builder.go
  pkg/deployment/reconcile/plan_builder_test.go
  pkg/deployment/reconcile/plan_builder_tls.go
  pkg/deployment/reconcile/plan_executor.go
  pkg/deployment/reconcile/timeouts.go
  pkg/deployment/resources/certificates_client_auth.go
  pkg/deployment/resources/certificates_tls.go
  pkg/util/k8sutil/secrets.go
Labels: 4 - Review, Team Clifton

#184 Fixed ID prefix for single servers
  pkg/deployment/members.go
  pkg/util/k8sutil/names.go
Labels: 4 - Review, Team Clifton

#183 Allow changing server group storage class.
  pkg/apis/deployment/v1alpha/plan.go
  pkg/apis/deployment/v1alpha/server_group_spec.go
  pkg/deployment/context_impl.go
  pkg/deployment/reconcile/action.go
  pkg/deployment/reconcile/action_add_member.go
  pkg/deployment/reconcile/action_cleanout_member.go
  pkg/deployment/reconcile/action_context.go
  pkg/deployment/reconcile/action_remove_member.go
  pkg/deployment/reconcile/action_renew_tls_ca_certificate.go
  pkg/deployment/reconcile/action_renew_tls_certificate.go
  pkg/deployment/reconcile/action_rotate_member.go
  pkg/deployment/reconcile/action_shutdown_member.go
  pkg/deployment/reconcile/action_upgrade_member.go
  pkg/deployment/reconcile/action_wait_for_member_up.go
  pkg/deployment/reconcile/context.go
  pkg/deployment/reconcile/plan_builder.go
  pkg/deployment/reconcile/plan_builder_storage.go
  pkg/deployment/reconcile/plan_builder_test.go
  pkg/deployment/reconcile/plan_executor.go
  pkg/util/k8sutil/events.go
Labels: 4 - Review, Team Clifton

#185 Use standard EventRecord to use event compression
  main.go
  pkg/deployment/deployment.go
  pkg/deployment/members.go
  pkg/deployment/reconcile/context.go
  pkg/deployment/resources/context.go
  pkg/deployment/resources/pod_inspector.go
  pkg/operator/operator_deployment.go
  pkg/operator/operator_deployment_relication.go
  pkg/operator/operator_local_storage.go
  pkg/replication/deployment_replication.go
  pkg/storage/local_storage.go
  pkg/util/k8sutil/events.go
Labels: 4 - Review, Team Clifton

#194 Adding downtimeAllowed field
  docs/Manual/Deployment/Kubernetes/DeploymentResource.md
  pkg/apis/deployment/v1alpha/deployment_spec.go
  pkg/apis/deployment/v1alpha/zz_generated.deepcopy.go
  pkg/deployment/reconcile/plan_builder.go
  pkg/deployment/reconcile/plan_builder_tls.go
  pkg/util/k8sutil/events.go
Labels: 4 - Review, Team Clifton

#187 Added tutorial for configuring DC2DC of Kubernetes
  docs/Manual/Tutorials/Kubernetes/DC2DC.md
Labels: 4 - Review, Team Clifton

#201 All operator Pods will now reach the Ready state.
  main.go
  manifests/templates/deployment-replication/rbac.yaml
  manifests/templates/deployment/rbac.yaml
  manifests/templates/storage/rbac.yaml
  pkg/operator/operator.go
  pkg/operator/operator_leader.go
  pkg/util/k8sutil/owner.go
Labels: 4 - Review, Team Clifton

#203 Log improvements
  deps/github.com/golang/glog/glog_redirect.go
  main.go
  pkg/logging/logger.go
Labels: 4 - Review, Team Clifton

#204 Fixed get/set Default flag for StorageClasses
  pkg/util/k8sutil/storageclass.go
Labels: 4 - Review, Team Clifton

#205 Documentation fixes
  docs/Manual/Deployment/Kubernetes/Authentication.md
  docs/Manual/Deployment/Kubernetes/DeploymentReplicationResource.md
  docs/Manual/Deployment/Kubernetes/DeploymentResource.md
  docs/Manual/Deployment/Kubernetes/DriverConfiguration.md
  docs/Manual/Deployment/Kubernetes/Troubleshooting.md
Labels: 2 - Working, 3 Documentation, 9 Ready to Merge

#208 Set a `role=leader` label on the Pod who won the leader election
  pkg/operator/operator_leader.go
  pkg/util/constants/constants.go
Labels: 4 - Review, Team Clifton

#206 Rotate server on changed arguments
  pkg/deployment/context_impl.go
  pkg/deployment/reconcile/context.go
  pkg/deployment/reconcile/plan_builder.go
  pkg/deployment/reconcile/plan_builder_context.go
  pkg/deployment/reconcile/plan_builder_test.go
  pkg/deployment/resources/pod_inspector.go
  tests/change_args_test.go
Labels: 4 - Review, Team Clifton
