Repository arangodb/kube-arangodb, pull requests merged in 2018-03, with the labels that each got.

#57 Detecting ImageID & ArangoDB version.
  pkg/apis/deployment/v1alpha/deployment_status.go
  pkg/apis/deployment/v1alpha/image_info.go
  pkg/apis/deployment/v1alpha/image_info_test.go
  pkg/apis/deployment/v1alpha/zz_generated.deepcopy.go
  pkg/deployment/deployment.go
  pkg/deployment/images.go
  pkg/deployment/pod_creator.go
  pkg/util/arangod/client.go
  pkg/util/k8sutil/pods.go
Labels: 9 Review Required

#66 Fixed immitable `mode` field.
  pkg/operator/operator_deployment.go
Labels: 9 Review Required

#65 Integrate with scaling web-UI
  pkg/deployment/cluster_informer.go
  pkg/deployment/cluster_updater.go
  pkg/deployment/deployment.go
  pkg/util/arangod/cluster.go
Labels: 9 Review Required

#68 Store accepted spec
  pkg/apis/deployment/v1alpha/authentication_spec.go
  pkg/apis/deployment/v1alpha/authentication_spec_test.go
  pkg/apis/deployment/v1alpha/deployment_mode.go
  pkg/apis/deployment/v1alpha/deployment_spec.go
  pkg/apis/deployment/v1alpha/deployment_spec_test.go
  pkg/apis/deployment/v1alpha/deployment_status.go
  pkg/apis/deployment/v1alpha/environment.go
  pkg/apis/deployment/v1alpha/monitoring_spec.go
  pkg/apis/deployment/v1alpha/monitoring_spec_test.go
  pkg/apis/deployment/v1alpha/rocksdb_spec.go
  pkg/apis/deployment/v1alpha/rocksdb_spec_test.go
  pkg/apis/deployment/v1alpha/server_group_spec.go
  pkg/apis/deployment/v1alpha/server_group_spec_test.go
  pkg/apis/deployment/v1alpha/storage_engine.go
  pkg/apis/deployment/v1alpha/sync_spec.go
  pkg/apis/deployment/v1alpha/sync_spec_test.go
  pkg/apis/deployment/v1alpha/tls_spec.go
  pkg/apis/deployment/v1alpha/tls_spec_test.go
  pkg/apis/deployment/v1alpha/zz_generated.deepcopy.go
  pkg/deployment/action_context.go
  pkg/deployment/cluster_scaling_integration.go
  pkg/deployment/deployment.go
  pkg/deployment/images.go
  pkg/deployment/members.go
  pkg/deployment/plan_builder.go
  pkg/deployment/plan_builder_test.go
  pkg/deployment/pod_creator.go
  pkg/deployment/pod_creator_agent_args_test.go
  pkg/deployment/pod_creator_coordinator_args_test.go
  pkg/deployment/pod_creator_dbserver_args_test.go
  pkg/deployment/pod_creator_single_args_test.go
  pkg/deployment/pvcs.go
  pkg/deployment/secrets.go
  pkg/deployment/services.go
  pkg/deployment/tls.go
  pkg/util/arangod/client.go
  pkg/util/k8sutil/test/events_test.go
  pkg/util/refs.go
  tests/auth_test.go
  tests/rocksdb_encryption_test.go
  tests/scale_test.go
  tests/simple_test.go
  tests/test_util.go
Labels: 9 Review Required

#70 Moved reconciliation code to separate package
  Makefile
  pkg/deployment/deployment.go
  pkg/deployment/deployment_inspector.go
  pkg/deployment/pod_inspector.go
  pkg/deployment/reconcile/action.go
  pkg/deployment/reconcile/action_add_member.go
  pkg/deployment/reconcile/action_cleanout_member.go
  pkg/deployment/reconcile/action_context.go
  pkg/deployment/reconcile/action_remove_member.go
  pkg/deployment/reconcile/action_rotate_member.go
  pkg/deployment/reconcile/action_shutdown_member.go
  pkg/deployment/reconcile/action_upgrade_member.go
  pkg/deployment/reconcile/action_wait_for_member_up.go
  pkg/deployment/reconcile/errors.go
  pkg/deployment/reconcile/plan_builder.go
  pkg/deployment/reconcile/plan_builder_test.go
  pkg/deployment/reconcile/plan_executor.go
  pkg/deployment/reconcile/reconcile_context.go
  pkg/deployment/reconcile/reconciler.go
  pkg/deployment/reconcile_context_impl.go
Labels: 9 Review Required

#64 add test for different deployments
  tests/deployments_test.go
Labels: 9 Review Required

#69 Test/different deployments resilient
  tests/deployments_test.go
Labels: 9 Review Required

#74 Also watch changes in PVCs and Services
  pkg/deployment/deployment.go
  pkg/deployment/deployment_inspector.go
  pkg/deployment/informers.go
  pkg/deployment/pod_informer.go
  pkg/deployment/resources/services.go
  pkg/util/k8sutil/services.go
Labels: 9 Review Required

#75 check result of api version call
  tests/deployments_test.go
  tests/test_util.go
Labels: 9 WIP

#77 Added terminated-pod cleanup to speed up re-creation of pods.
  pkg/deployment/context_impl.go
  pkg/deployment/deployment_inspector.go
  pkg/deployment/resources/context.go
  pkg/deployment/resources/pod_cleanup.go
  pkg/deployment/resources/pod_creator.go
  pkg/deployment/resources/pod_inspector.go
  tests/resilience_test.go
Labels: 9 Review Required

#78 Fix scale-up
  pkg/deployment/reconcile/plan_executor.go
Labels: 9 Review Required

#59 Feature/add tests for immutable cluster parameters
  tests/immutable_test.go
  tests/test_util.go
Labels: 9 WIP

#80 Store & compare hash of secrets.
  pkg/apis/deployment/v1alpha/conditions.go
  pkg/apis/deployment/v1alpha/deployment_status.go
  pkg/apis/deployment/v1alpha/secret_hashes.go
  pkg/apis/deployment/v1alpha/zz_generated.deepcopy.go
  pkg/deployment/deployment.go
  pkg/deployment/deployment_inspector.go
  pkg/deployment/informers.go
  pkg/deployment/resources/secret_hashes.go
  pkg/util/k8sutil/events.go
Labels: 9 Review Required

#81 AsOwner no longer things the owner refers to a controller. It refers to the ArangoDeployment
  pkg/apis/deployment/v1alpha/deployment.go
  pkg/apis/storage/v1alpha/local_storage.go
Labels: 9 Review Required

#82 Added detection on unschedulable pods
  pkg/apis/deployment/v1alpha/conditions.go
  pkg/deployment/resources/pod_inspector.go
  pkg/util/k8sutil/events.go
  pkg/util/k8sutil/pods.go
Labels: 9 Review Required

#76 add upgrade tests
  tests/auth_test.go
  tests/deployments_test.go
  tests/rocksdb_encryption_test.go
  tests/simple_test.go
  tests/test_util.go
  tests/upgrade_test.go
Labels: 9 Review Required, 9 WIP

#91 Tracking recent pod terminations
  pkg/apis/deployment/v1alpha/member_status.go
  pkg/apis/deployment/v1alpha/member_status_test.go
  pkg/apis/deployment/v1alpha/zz_generated.deepcopy.go
  pkg/deployment/reconcile/action_rotate_member.go
  pkg/deployment/reconcile/action_upgrade_member.go
  pkg/deployment/resources/pod_inspector.go
Labels: 9 Review Required

#88 Tests/modes
  Makefile
  manifests/.gitignore
  manifests/templates/deployment/rbac.yaml
  manifests/templates/test/rbac.yaml
  tests/environments_test.go
  tools/manifests/manifest_builder.go
Labels: 9 Review Required

#36 begin to add tests for `apis/storage/v1alpha`
  Makefile
  pkg/apis/storage/v1alpha/local_storage_spec_test.go
  pkg/apis/storage/v1alpha/storage_class_spec_test.go
Labels: 9 Review Required
