Repository arangodb/kube-arangodb, pull requests merged in 2018-04, with the labels that each got.

#93 Fixing PV cleanup
  pkg/storage/pv_cleanup.go
  pkg/storage/pv_inspector.go
Labels: 9 Review Required

#95 Check contents of persisted volume when dbserver is restarting
  pkg/apis/deployment/v1alpha/member_status.go
  pkg/deployment/images.go
  pkg/deployment/resources/pod_creator.go
  pkg/deployment/resources/pod_inspector.go
  pkg/util/k8sutil/pods.go
Labels: 9 Review Required

#98 Adding CHANGELOG.md generation
  CHANGELOG.md
  Makefile
  tools/release/release.go
Labels: 9 Review Required

#99 Patch latest version number in README
  Makefile
  scripts/patch_readme.sh
  tools/release/release.go
Labels: 9 Review Required

#100 Added LivenessProbe & Readiness probe
  main.go
  manifests/templates/deployment/deployment.yaml
  manifests/templates/storage/deployment.yaml
  pkg/operator/operator.go
  pkg/operator/operator_deployment.go
  pkg/operator/operator_local_storage.go
  pkg/util/probe/health.go
  pkg/util/probe/ready.go
Labels: 9 Review Required

#101 Adding GettingStarted page and structuring docs for website
  README.md
  docs/Manual/GettingStarted/kube-arangodb/README.md
  docs/Manual/Programs/kube-arangodb/README.md
  docs/Manual/Programs/kube-arangodb/config_and_secrets.md
  docs/Manual/Programs/kube-arangodb/custom_resource.md
  docs/Manual/Programs/kube-arangodb/metrics.md
  docs/Manual/Programs/kube-arangodb/scaling.md
  docs/Manual/Programs/kube-arangodb/services_and_loadbalancer.md
  docs/Manual/Programs/kube-arangodb/storage.md
  docs/Manual/Programs/kube-arangodb/storage_resource.md
  docs/Manual/Programs/kube-arangodb/tls.md
  docs/Manual/Programs/kube-arangodb/upgrading.md
  docs/Manual/Programs/kube-arangodb/usage.md
  docs/README.md
Labels: 9 Review Required

#96 Adding chaos-monkey for deployments
  Makefile
  main.go
  manifests/templates/deployment/deployment.yaml
  pkg/apis/deployment/v1alpha/chaos_spec.go
  pkg/apis/deployment/v1alpha/deployment_spec.go
  pkg/apis/deployment/v1alpha/percent.go
  pkg/apis/deployment/v1alpha/zz_generated.deepcopy.go
  pkg/deployment/chaos/context.go
  pkg/deployment/chaos/errors.go
  pkg/deployment/chaos/monkey.go
  pkg/deployment/deployment.go
  pkg/operator/operator.go
  pkg/operator/operator_deployment.go
  tools/manifests/manifest_builder.go
  tools/release/release.go
Labels: 9 Review Required

#103 Changed TLSSpec.TTL to new string based `Duration` type
  pkg/apis/deployment/v1alpha/duration.go
  pkg/apis/deployment/v1alpha/tls_spec.go
  pkg/apis/deployment/v1alpha/tls_spec_test.go
  pkg/apis/deployment/v1alpha/zz_generated.deepcopy.go
  pkg/deployment/resources/tls.go
  tests/scale_test.go
Labels: 9 Review Required

#102 Added automatic renewal of TLS server certificates
  pkg/apis/deployment/v1alpha/plan.go
  pkg/deployment/context_impl.go
  pkg/deployment/reconcile/action_context.go
  pkg/deployment/reconcile/action_renew_tls_certificate.go
  pkg/deployment/reconcile/context.go
  pkg/deployment/reconcile/plan_builder.go
  pkg/deployment/reconcile/plan_builder_test.go
  pkg/deployment/reconcile/plan_executor.go
  pkg/util/k8sutil/secrets.go
Labels: 9 Review Required

#107 Quickly fail when deployment no longer exists
  pkg/deployment/deployment.go
  pkg/deployment/deployment_inspector.go
  pkg/storage/local_storage.go
Labels: 9 Review Required

#108 Doc - Follow file name conventions of main docs, move to Tutorials
  README.md
  docs/Manual/Deployment/Kubernetes/ConfigAndSecrets.md
  docs/Manual/Deployment/Kubernetes/DeploymentResource.md
  docs/Manual/Deployment/Kubernetes/Metrics.md
  docs/Manual/Deployment/Kubernetes/README.md
  docs/Manual/Deployment/Kubernetes/Scaling.md
  docs/Manual/Deployment/Kubernetes/ServicesAndLoadBalancer.md
  docs/Manual/Deployment/Kubernetes/Storage.md
  docs/Manual/Deployment/Kubernetes/StorageResource.md
  docs/Manual/Deployment/Kubernetes/Tls.md
  docs/Manual/Deployment/Kubernetes/Upgrading.md
  docs/Manual/Deployment/Kubernetes/Usage.md
  docs/Manual/Tutorials/Kubernetes/README.md
  docs/README.md
Labels: 3 Documentation

#89 Tests/multi deployment
  pkg/apis/storage/v1alpha/local_storage_spec_test.go
  tests/deployments_test.go
Labels: 9 Review Required

#116 Fixed expected value for ENGINE file in init container of dbserver.
  pkg/apis/deployment/v1alpha/storage_engine.go
  pkg/deployment/resources/pod_creator.go
Labels: 1 Bug, 9 Waiting for Jenkins

#123 Fixed down/upgrading resilient single deployments.
  pkg/deployment/reconcile/action_wait_for_member_up.go
Labels: 1 Bug, 9 Waiting for Jenkins

#124 BREAKING CHANGE: Deployment mode ResilientSingle renamed to ActiveFailover
  README.md
  docs/Manual/Deployment/Kubernetes/DeploymentResource.md
  pkg/apis/deployment/v1alpha/deployment_mode.go
  pkg/apis/deployment/v1alpha/deployment_mode_test.go
  pkg/apis/deployment/v1alpha/server_group_spec.go
  pkg/apis/deployment/v1alpha/server_group_spec_test.go
  pkg/apis/deployment/v1alpha/sync_spec_test.go
  pkg/deployment/reconcile/action_wait_for_member_up.go
  pkg/deployment/reconcile/plan_builder.go
  pkg/deployment/reconcile/plan_builder_test.go
  pkg/deployment/resources/pod_creator.go
  pkg/deployment/resources/pod_creator_single_args_test.go
  tests/cursor_test.go
  tests/deployments_test.go
  tests/simple_test.go
  tests/test_util.go
  tests/upgrade_test.go
Labels: 9 Review Required
