Repository arangodb/kube-arangodb, pull requests merged in 2019-07, with the labels that each got.

#397 Supported version - IBM Cloud 1.13
  README.md
Labels: 3 Documentation

#423 ArangoDB version in membership status
  CHANGELOG.md
  pkg/apis/deployment/v1alpha/member_status.go
  pkg/deployment/resources/pod_creator.go
Labels: 1 Feature, Team Clifton

#420 Feature/restart pods on sidecar changes
  CHANGELOG.md
  docs/Manual/Tutorials/Kubernetes/bare-metal.md
  pkg/apis/deployment/v1alpha/deployment_status.go
  pkg/apis/deployment/v1alpha/member_status.go
  pkg/deployment/reconcile/action_context.go
  pkg/deployment/reconcile/action_rotate_member.go
  pkg/deployment/reconcile/plan_builder.go
  pkg/deployment/resources/member_cleanup.go
  tests/load_balancer_source_ranges_test.go
  tests/sidecar_test.go
  tests/test_util.go
Labels: 9 WIP
