Repository arangodb/kube-arangodb, pull requests merged in 2019-03, with the labels that each got.

#347 Feature/upgrade tests
  Makefile
  manifests/templates/test/rbac.yaml
  tests/environments_test.go
  tests/operator_upgrade_test.go
  tests/test_util.go
  tests/upgrade_test.go
Labels: 2 - Working

#348 Feature/sync test same dc
  tests/sync_test.go
  tests/test_util.go
Labels: 2 - Working

#349 Added MY_NODE_NAME and NODE_NAME envs for all pods.
  pkg/util/constants/constants.go
  pkg/util/k8sutil/pods.go
Labels: 2 - Working

#351 remove storage class deployment from EKS tutorial
  docs/Manual/Tutorials/Kubernetes/EKS.md
Labels: 2 - Working, 3 Documentation

#352 Added pod disruption budgets in production mode.
  CHANGELOG.md
  manifests/templates/deployment/rbac.yaml
  pkg/apis/deployment/v1alpha/deployment_mode.go
  pkg/apis/deployment/v1alpha/deployment_spec.go
  pkg/deployment/deployment.go
  pkg/deployment/deployment_inspector.go
  pkg/deployment/resources/pdbs.go
  tests/pdb_test.go
Labels: 2 - Working

#355 Make cleanoutserver step mandatory in drain documentation.
  docs/Manual/Deployment/Kubernetes/Drain.md
Labels: 2 - Working

#350 ArangoSync tests
  Makefile
  manifests/templates/test/rbac.yaml
  pkg/apis/deployment/v1alpha/deployment_spec.go
  pkg/apis/deployment/v1alpha/sync_spec.go
  pkg/apis/deployment/v1alpha/zz_generated.deepcopy.go
  pkg/deployment/access_package.go
  pkg/deployment/resources/pod_creator.go
  pkg/util/k8sutil/client.go
  scripts/kube_run_sync_tests.sh
  tests/sync/Dockerfile
  tests/sync/main.go
  tests/sync_test.go
Labels: 2 - Working

#329 Documentation/correct for copy paster
  docs/Manual/Tutorials/Kubernetes/bare-metal.md
Labels: 2 - Working, 3 Documentation

#361 Allow to disable probes
  docs/Manual/Deployment/Kubernetes/DeploymentResource.md
  pkg/apis/deployment/v1alpha/server_group_spec.go
  pkg/apis/deployment/v1alpha/zz_generated.deepcopy.go
  pkg/deployment/resources/pod_creator.go
  pkg/util/k8sutil/probes.go
  pkg/util/k8sutil/probes_test.go
Labels: 2 - Working

#357 Volume resizing
  pkg/deployment/reconcile/plan_builder_storage.go
  pkg/deployment/resources/pvc_inspector.go
  pkg/util/k8sutil/events.go
  pkg/util/k8sutil/pvc.go
  tests/persistent_volumes_test.go
Labels: 2 - Working, ready

#356 Reboot
  Makefile
  examples/reboot-pod.yaml
  reboot.go
Labels: 2 - Working, ready

#325 Randomize Root Password
  docs/Manual/Deployment/Kubernetes/DeploymentResource.md
  pkg/apis/deployment/v1alpha/bootstrap.go
  pkg/apis/deployment/v1alpha/conditions.go
  pkg/apis/deployment/v1alpha/deployment_spec.go
  pkg/apis/deployment/v1alpha/zz_generated.deepcopy.go
  pkg/deployment/bootstrap.go
  pkg/deployment/deployment_inspector.go
  pkg/deployment/resources/pod_inspector.go
  pkg/util/k8sutil/names.go
  pkg/util/k8sutil/secrets.go
Labels: 2 - Working, ready
