Repository arangodb/kube-arangodb, pull requests merged in 2019-05, with the labels that each got.

#323 ArangoExporter support
  pkg/apis/deployment/v1alpha/deployment_spec.go
  pkg/apis/deployment/v1alpha/metrics_spec.go
  pkg/apis/deployment/v1alpha/server_group.go
  pkg/apis/deployment/v1alpha/zz_generated.deepcopy.go
  pkg/deployment/images.go
  pkg/deployment/reconcile/plan_builder.go
  pkg/deployment/resources/pod_creator.go
  pkg/deployment/resources/secrets.go
  pkg/util/k8sutil/constants.go
  pkg/util/k8sutil/pods.go
  pkg/util/k8sutil/secrets.go
  pkg/util/k8sutil/util.go
Labels: 2 - Working, ready

#369 Supported versions
  README.md
Labels: 3 Documentation, 9 WIP

#390 Updates list of supported versions - IBM Cloud
  README.md
Labels: 3 Documentation
